### PR TITLE
Absinthe telemetry

### PR DESCRIPTION
**Pull request by scottming**
On the basis of @binaryseed 's work, I added parent-related logic and absinthe-related aggregation and transaction, I am not very familiar with newrelic, so there should be places to improve, if you have any suggestions, welcome to leave a comment.

You can use this [repository](https://github.com/scottming/products-demo) to check the final result

**query**

```gql
query getAllProducts {
  allProducts {
    id
    sku
    package
    dimensions {
      size
      weight
    }
    createdBy {
      totalProductsCreated
      email
      profile {
        info
      }
    }
  }
}
```

### Transactions

image

### Transaction trace

image

### CODE REVIEW

**Comment by jadlr** [comment]
Is there any update on this? We'd be very interested in absinthe traces in new relic. :pray:

**Comment by tansanDOTeth** [comment]
I would love this.

**Comment by tansanDOTeth** [comment]
@scottming 🐐

**Comment by binaryseed** [comment]
Closing in favor of https://github.com/newrelic/elixir_agent/pull/471

**Pull request closed without merging**
