### PR TITLE
Bump version, update changelog

### PR DESCRIPTION
**Pull request by tpitale**

### CODE REVIEW

**Comment by binaryseed** [comment]
Worth noting https://github.com/newrelic/elixir_agent/pull/424 too

**Comment by binaryseed** [comment]
`docker-compose: command not found`

That needs to be changed to `docker compose`

**Comment by binaryseed** [comment]
I seem to have lost maintainer rights on the repo @tpitale

**Comment by tpitale** [comment]
Sent invite again.

Also, reached out on Linkedin to share other details 😁

**Comment by binaryseed** [comment]
I got the bandit PR up and running, if you want to include that before releasing https://github.com/newrelic/elixir_agent/pull/445

**Comment by tpitale** [comment]
Good idea.

**Pull request merged**
