### PR TITLE
Test on latest supported versions

### PR DESCRIPTION
**Pull request by binaryseed**
Updates tests to run on most recent 4 Elixir versions, dropping older versions that are no longer receiving Elixir security patches

- https://hexdocs.pm/elixir/1.18.0-rc.0/compatibility-and-deprecations.html

### CODE REVIEW

**Comment by binaryseed** [comment]
@tpitale Any chance we can allow maintainers to merge their own PRs?

**Comment by tpitale** [comment]
> @tpitale Any chance we can allow maintainers to merge their own PRs?

I'll reach out to security and see what they say. Everything has been on lockdown lately (I had to get my access restored, even).

**Review by tpitale — APPROVED** [review]

**Comment by tpitale** [comment]
Going to merge this for now, made request to security to update permissions.

**Comment by tpitale** [comment]
> I believe only members with push access can merge from branches, so that would be restricted to only org members that have repo access.

**Pull request merged**
