### PR TITLE
Misc doc changes

### PR DESCRIPTION
**Pull request by kianmeng**
This PR introduces two changes to module config which includes:
- Changelog link shown in Hex module info page.
- Function header link to GitHub source URL based on tagged version instead of `master` branch.

### CODE REVIEW

**Comment by binaryseed** [comment]
Thanks! If you can sign the CLA, I'll merge this!

**Comment by binaryseed** [comment]
@kianmeng if you could sign the CLA, these would be nice changes to merge :)

**Comment by binaryseed** [comment]
I've pulled these changes in myself, closing due to no response...

**Comment by kianmeng** [comment]
> I've pulled these changes in myself, closing due to no response...

@binaryseed Sorry, I've missed the email notifications. Thanks for adding the changes.

**Pull request closed without merging**
