### PR TITLE
Only get CPU utilization if os_mon's cpu_sup is enabled

### PR DESCRIPTION
**Pull request by tomtaylor**
This ensures that we return nil, not 0, if cpu_sup is disabled, and prevents endless log warnings about cpu_sup not being enabled.

### CODE REVIEW

**Comment by binaryseed** [comment]
Are you manually turning off `cpu_sup`?. The agent includes the `:os_mon` application...

**Comment by tomtaylor** [comment]
Yeah, that's right.

**Comment by binaryseed** [comment]
Is it just the shutdown bug you are trying to avoid or is there another reason you don't want it started?

**Comment by tomtaylor** [comment]
No, it's just the shutdown bug. If we disable it in the `os_mon` config ourselves the agent will still make calls to `cpu_util`, littering our logs with warnings about it not being started every few seconds.

**Comment by tomtaylor** [comment]
Hey @binaryseed, any more thoughts on this?

**Pull request merged**
